name: video_call
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  get_it:
  get_storage:
  zego_zim: ^2.13.1
  date_format: ^2.0.7
  badges: ^2.0.3
  provider: ^6.0.3
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  filesystem_picker: ^2.0.0
  file_picker: ^4.0.6
  emoji_picker_flutter: ^1.3.0
  flutter_easyrefresh: ^2.2.1
  photo_view: ^0.14.0
  video_player: ^2.4.7
  universal_io: 2.0.4
  flutter_emoji: 2.4.0

  flutter:
    sdk: flutter
#  zego_uikit_prebuilt_call: ^4.4.1
#  zego_uikit_signaling_plugin: ^2.7.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


dependency_overrides:
  flutter_screenutil: ^5.9.0

flutter: 
  uses-material-design: true

