// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIvnUozy1VINC8QC1xK_rHx4mk6m9HEM',
    appId: '1:1029656996388:web:a92f394ba814220b7b86b1',
    messagingSenderId: '1029656996388',
    projectId: 'vedeocalldemo',
    authDomain: 'vedeocalldemo.firebaseapp.com',
    storageBucket: 'vedeocalldemo.appspot.com',
    measurementId: 'G-TYG2BMW2RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsAobNX6osxFiBzFifcd0egJ2uhpR9Iy8',
    appId: '1:1029656996388:android:6a8ea109e4ae44e47b86b1',
    messagingSenderId: '1029656996388',
    projectId: 'vedeocalldemo',
    storageBucket: 'vedeocalldemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifyZ8j150Yj451sF3elA5Svj0gab6dpQ',
    appId: '1:1029656996388:ios:908fac4ab8f118017b86b1',
    messagingSenderId: '1029656996388',
    projectId: 'vedeocalldemo',
    storageBucket: 'vedeocalldemo.appspot.com',
    iosBundleId: 'com.example.videoCall',
  );
}
